[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@fhenixprotocol/cofhe-contracts/=node_modules/@fhenixprotocol/cofhe-contracts/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
